GET http://localhost:3001/book HTTP/1.1
Content-Type: application/json 

###

POST http://localhost:3001/book HTTP/1.1
Content-Type: application/json

{
    "titel" : "Harry"
}

###

PUT http://localhost:3001/book/1 HTTP/1.1
Content-Type: application/json

{
    "titel" : "Harry poter"
}

###

DELETE http://localhost:3001/book/1 HTTP/1.1
Content-Type: application/json